import os
import pandas as pd
from sqlalchemy import text
from db_config import get_db_engine

# Path to the cleaned CSV file generated by 02_process.py
CSV_PATH = os.path.join("data", "clean", "kafka_processed_weather.csv")


def initialize_postgis_table(engine):
    """Ensure PostGIS extension and weather_alerts table exist."""
    create_table_query = text("""
        CREATE EXTENSION IF NOT EXISTS postgis;

        CREATE TABLE IF NOT EXISTS weather_alerts (
            id SERIAL PRIMARY KEY,
            station_id VARCHAR(100),
            station_name VARCHAR(255),
            state VARCHAR(100),
            temperature DOUBLE PRECISION,
            humidity DOUBLE PRECISION,
            rainfall DOUBLE PRECISION,
            severity VARCHAR(50),
            geom GEOMETRY(Point, 4326),
            processed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
        );

        CREATE INDEX IF NOT EXISTS idx_weather_alerts_geom 
        ON weather_alerts USING GIST (geom);
    """)

    with engine.begin() as connection:
        connection.execute(create_table_query)
    print("✓ PostGIS extension and weather_alerts table initialized.")


def sync_csv_to_postgis():
    """Reads cleaned CSV data and inserts spatial records into PostGIS."""
    if not os.path.exists(CSV_PATH):
        print(f"Error: {CSV_PATH} not found. Ensure 02_process.py has been executed.")
        return

    df = pd.read_csv(CSV_PATH)

    if df.empty:
        print("CSV file is empty. No records to ingest.")
        return

    engine = get_db_engine()

    # Step A: Initialize Database Schema & PostGIS Extension
    initialize_postgis_table(engine)

    # Step B: Insert records into PostGIS using ST_SetSRID & ST_MakePoint
    insert_query = text("""
        INSERT INTO weather_alerts (
            station_id, station_name, state, temperature, humidity, rainfall, severity, geom
        ) VALUES (
            :station_id, :station_name, :state, :temperature, :humidity, :rainfall, :severity,
            ST_SetSRID(ST_MakePoint(:longitude, :latitude), 4326)
        );
    """)

    records_inserted = 0
    with engine.begin() as connection:
        for _, row in df.iterrows():
            params = {
                "station_id": str(row.get("station_id", "UNKNOWN")),
                "station_name": str(row.get("station_name", "Unknown Station")),
                "state": str(row.get("state", "India")),
                "temperature": float(row.get("temperature", 0.0)) if pd.notnull(row.get("temperature")) else None,
                "humidity": float(row.get("humidity", 0.0)) if pd.notnull(row.get("humidity")) else None,
                "rainfall": float(row.get("rainfall", 0.0)) if pd.notnull(row.get("rainfall")) else None,
                "severity": str(row.get("severity", "Normal")),
                "longitude": float(row.get("longitude", 77.5946)),
                "latitude": float(row.get("latitude", 12.9716)),
            }
            connection.execute(insert_query, params)
            records_inserted += 1

    print(f"✓ Successfully ingested {records_inserted} records into PostGIS database!")


if __name__ == "__main__":
    sync_csv_to_postgis()