import type { Incident, Alert } from './types'

export const lifecycle = ['Detected', 'Verified', 'Acknowledged', 'Assigned', 'Responding', 'Resolved'] as const

export const incidents: Incident[] = [
  {
    id: 1,
    event: 'Heatwave',
    name: 'Delhi NCR Heatwave',
    place: 'Delhi NCR',
    state: 'Delhi',
    district: 'Central Delhi',
    severity: 'critical',
    value: '45.2°C',
    source: 'IMD API',
    reports: 231,
    confidence: 96,
    consensus: 'High',
    independentSources: '4 / 5',
    status: 'Responding',
    impact: '12.4M residents · 84 hospitals · 3,120 km²',
    lat: 28.6139,
    lng: 77.2090,
    time: '41 min ago',
    alertText: 'Maximum temperature 6°C above seasonal average.',
    areaAffected: {
      area: '3,120 km²',
      population: '12.4M',
      hospitals: '84 hospitals',
      schools: '42 schools',
      roads: '8 major highways',
      infrastructure: '12 substations, 3 power plants',
      districts: '11 districts',
    },
    evidence: [
      { name: 'IMD API', status: 'verified' },
      { name: 'Satellite / sensor', status: 'verified' },
      { name: 'Citizen reports', status: 'verified' },
      { name: 'Public posts', status: 'pending' },
    ],
  },
  {
    id: 2,
    event: 'Heavy Rainfall',
    name: 'Bengaluru Urban Flooding',
    place: 'Bengaluru',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    severity: 'high',
    value: '142 mm',
    source: 'Citizen reports',
    reports: 148,
    confidence: 92,
    consensus: 'High',
    independentSources: '4 / 5',
    status: 'Acknowledged',
    impact: '2.1M residents · 18 transit corridors · 640 km²',
    lat: 12.9716,
    lng: 77.5946,
    time: '8 min ago',
    alertText: 'Urban flooding reported across 6 districts. 142 mm rainfall recorded.',
    areaAffected: {
      area: '640 km²',
      population: '2.1M',
      hospitals: '18 hospitals',
      schools: '67 schools',
      roads: '18 transit corridors',
      infrastructure: '6 drainage pumps, 2 metro lines',
      districts: '6 districts',
    },
    evidence: [
      { name: 'Citizen reports', status: 'verified' },
      { name: 'Weather API', status: 'verified' },
      { name: 'Public posts', status: 'verified' },
      { name: 'Government API', status: 'pending' },
    ],
  },
  {
    id: 3,
    event: 'Cyclone',
    name: 'Odisha Coast Cyclone',
    place: 'Odisha Coast',
    state: 'Odisha',
    district: 'Puri',
    severity: 'critical',
    value: '118 km/h',
    source: 'Satellite feed',
    reports: 392,
    confidence: 97,
    consensus: 'High',
    independentSources: '5 / 5',
    status: 'Verified',
    impact: '4.8M residents · 126 shelters · 14 coastal blocks',
    lat: 19.8135,
    lng: 85.8312,
    time: '14 min ago',
    alertText: 'Severe cyclonic storm moving north-west. Coastal evacuation advised.',
    areaAffected: {
      area: '14 coastal blocks',
      population: '4.8M',
      hospitals: '32 hospitals',
      schools: '126 schools (shelters)',
      roads: '4 national highways',
      infrastructure: '2 ports, 14 coastal blocks',
      districts: '14 districts',
    },
    evidence: [
      { name: 'Satellite / sensor', status: 'verified' },
      { name: 'IMD API', status: 'verified' },
      { name: 'Government API', status: 'verified' },
      { name: 'Citizen reports', status: 'verified' },
      { name: 'Public posts', status: 'verified' },
    ],
  },
  {
    id: 4,
    event: 'Extreme Wind',
    name: 'Rajasthan Windstorm',
    place: 'Rajasthan',
    state: 'Rajasthan',
    district: 'Jaisalmer',
    severity: 'moderate',
    value: '72 km/h',
    source: 'Weather API',
    reports: 62,
    confidence: 88,
    consensus: 'Medium',
    independentSources: '3 / 5',
    status: 'Detected',
    impact: '410k residents · 12 substations · 890 km²',
    lat: 26.9155,
    lng: 70.9083,
    time: '1 hr ago',
    alertText: 'High-velocity winds across desert districts. Structural damage risk.',
    areaAffected: {
      area: '890 km²',
      population: '410k',
      hospitals: '6 hospitals',
      schools: '23 schools',
      roads: '3 state highways',
      infrastructure: '12 substations, 4 wind farms',
      districts: '3 districts',
    },
    evidence: [
      { name: 'Weather API', status: 'verified' },
      { name: 'Satellite / sensor', status: 'verified' },
      { name: 'Public posts', status: 'pending' },
    ],
  },
  {
    id: 5,
    event: 'Flood',
    name: 'Siliguri Flood',
    place: 'Siliguri, West Bengal',
    state: 'West Bengal',
    district: 'Darjeeling',
    severity: 'high',
    value: 'Alert level 3',
    source: 'Public posts',
    reports: 186,
    confidence: 91,
    consensus: 'High',
    independentSources: '4 / 5',
    status: 'Assigned',
    impact: '1.6M residents · 42 schools · 1,200 km²',
    lat: 26.7271,
    lng: 88.3953,
    time: '26 min ago',
    alertText: 'River levels above danger mark near low-lying settlements.',
    areaAffected: {
      area: '1,200 km²',
      population: '1.6M',
      hospitals: '14 hospitals',
      schools: '42 schools',
      roads: 'NH-31, NH-10, 6 state roads',
      infrastructure: '2 railway junctions, 1 airport',
      districts: '4 districts',
    },
    evidence: [
      { name: 'Public posts', status: 'verified' },
      { name: 'Government API', status: 'verified' },
      { name: 'Citizen reports', status: 'verified' },
      { name: 'Satellite / sensor', status: 'pending' },
    ],
  },
  {
    id: 6,
    event: 'Thunderstorm',
    name: 'Maharashtra Thunderstorm',
    place: 'Maharashtra',
    state: 'Maharashtra',
    district: 'Pune',
    severity: 'low',
    value: '64 strikes/hr',
    source: 'Lightning API',
    reports: 44,
    confidence: 84,
    consensus: 'Medium',
    independentSources: '3 / 5',
    status: 'Detected',
    impact: '280k residents · 9 substations · 320 km²',
    lat: 18.5204,
    lng: 73.8567,
    time: '2 hr ago',
    alertText: 'Active lightning detected over western ghats region.',
    areaAffected: {
      area: '320 km²',
      population: '280k',
      hospitals: '9 hospitals',
      schools: '18 schools',
      roads: '2 state highways',
      infrastructure: '9 substations',
      districts: '2 districts',
    },
    evidence: [
      { name: 'Lightning API', status: 'verified' },
      { name: 'Weather API', status: 'verified' },
      { name: 'Citizen reports', status: 'pending' },
    ],
  },
]

export const alerts: Alert[] = [
  {
    sev: 'critical',
    event: 'Cyclone',
    place: 'Odisha Coast',
    time: '14 min ago',
    text: 'Severe cyclonic storm moving north-west. Coastal evacuation advised.',
    confidence: '97%',
    source: 'Satellite + IMD',
    incidentId: 3,
    status: 'Verified',
  },
  {
    sev: 'high',
    event: 'Heavy Rainfall',
    place: 'Bengaluru, Karnataka',
    time: '8 min ago',
    text: 'Urban flooding reported across 6 districts. 142 mm rainfall recorded.',
    confidence: '92%',
    source: 'Citizen reports + radar',
    incidentId: 2,
    status: 'Acknowledged',
  },
  {
    sev: 'high',
    event: 'Flood',
    place: 'Siliguri, West Bengal',
    time: '26 min ago',
    text: 'River levels above danger mark near low-lying settlements.',
    confidence: '91%',
    source: 'Public posts + gauges',
    incidentId: 5,
    status: 'Assigned',
  },
  {
    sev: 'critical',
    event: 'Heatwave',
    place: 'Delhi NCR',
    time: '41 min ago',
    text: 'Maximum temperature 6°C above seasonal average.',
    confidence: '96%',
    source: 'IMD API + stations',
    incidentId: 1,
    status: 'Responding',
  },
  {
    sev: 'moderate',
    event: 'Extreme Wind',
    place: 'Rajasthan',
    time: '1 hr ago',
    text: 'High-velocity winds across desert districts. Structural damage risk.',
    confidence: '88%',
    source: 'Weather API',
    incidentId: 4,
    status: 'Detected',
  },
]

export const statesData = [
  ['Odisha', 86],
  ['Karnataka', 72],
  ['West Bengal', 64],
  ['Maharashtra', 57],
  ['Rajasthan', 43],
]

export const sourcesData = [
  ['APIs', 46],
  ['Citizen reports', 24],
  ['Public posts', 15],
  ['Websites', 9],
  ['Datasets', 6],
]

export const incidentTypeData = [
  ['Heavy Rain', 82],
  ['Flood', 68],
  ['Heatwave', 54],
  ['Thunderstorm', 46],
  ['Cyclone', 30],
  ['Landslide', 21],
  ['Other', 12],
]

export const aiClassificationData = [
  ['Flood', 31],
  ['Heatwave', 24],
  ['Rainfall', 19],
  ['Cyclone', 14],
  ['Other', 12],
]

export const aiRiskRows = [
  ['Flood', 'Bengaluru', 'HIGH', '92%', '148'],
  ['Heatwave', 'Delhi NCR', 'HIGH', '96%', '231'],
  ['Cyclone', 'Odisha Coast', 'CRITICAL', '97%', '392'],
]

export const filterOptions = {
  state: ['All India', 'Delhi', 'Karnataka', 'Odisha', 'Rajasthan', 'West Bengal', 'Maharashtra'],
  district: ['All districts'],
  eventType: ['All events', 'Heatwave', 'Heavy Rainfall', 'Cyclone', 'Extreme Wind', 'Flood', 'Thunderstorm'],
  severity: ['All severities', 'critical', 'high', 'moderate', 'low'],
  dataSource: ['All sources', 'IMD API', 'Citizen reports', 'Satellite feed', 'Weather API', 'Public posts', 'Lightning API'],
}
